version: "3.8"
services:
  pe-parser:
    container_name: pe-parser
    build:
      context: ./pe-parser
      dockerfile: Dockerfile
      args:
        PORT: 3000
    env_file:
      - ./pe-parser/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./pe-parser:/app
      - ./pe-parser/out:/app/out
      - /app/node_modules
      - /dist
